### PR TITLE
5 Update food

### LINKED ISSUE #5: User can update a food item
As a user,
When I click on the update button next to any food in my food list,
The food name and time should be editable, and
I should see save and cancel buttons, and

### LINKED ISSUE #7: User can get a confirmation when it update food
As a user,
When am updating a food and I click save,
I should see a message that the food was successfully updated, and
I should see update and delete buttons next to the food I updated, and
I should see my changes reflected in the food name and/or time.

### LINKED ISSUE #10: User decided to cancel the update of a food item
``` Don't do it before user story 7 User can get confirmations of update food```
As a user,
When I am updating a food click cancel,
I should see a message that the action was successfully cancelled, and
I should see update and delete buttons next to the food I updated, and
I should see food name and/or time return to their previous values.

### PR DESCRIPTION
**Pull request by mngatewood**
- [ ] Wrote Tests
- [x] Implemented
- [ ] Reviewed

# Necessary checkmarks:
- [ ] All Tests are Passing
- [x] The code will run locally

## Type of change
- [x] New feature
- [ ] Bug Fix

# Implements: Update Food
## Description of Changes

* adds update food dialog on click edit button
* adds editable state to name and time on click edit button
* adds cancel update and save buttons
* adds fetch POST food_entries/reaction_entries function
* adds action/reducer for update food

closes #5 
closes #7 
closes #10 

# Check the correct boxes
- [x] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

# Testing Changes
- [ ] No Tests have been changed
- [ ] Some Tests have been changed
- [ ] All of the Tests have been changed(Please describe what in the world happened)

# Checklist:

- [ ] My code has no unused/commented out code
- [x] I have reviewed my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have fully tested my code

# Please include a link to a gif of how you feel about this branch:

### CODE REVIEW

**Comment by mngatewood** [comment]
@prestonjarnagin @Diazblack @Q-Win This PR is predicated on adding a "name" field to food_entries and reaction_entries.  Currently, the user is only able to update the time in the entries tables.  If the user wants to change the name, we will have to send a PATCH request to foods/reactions table.  This would be find, but if I change the name in the foods/reactions table, then it is going to change ALL instances of this food.  I don't think this is desirable.  If I want to go back and change "coffee" to "coffee with creamer' for today, I don't want all instances of coffee to change to coffee with creamer.  The only logical approach to this problem is to include the name of the food/reaction in the entries table.  This will also allow the FE app to only make a single PATCH request to the entries table without having to affect the foods/reactions tables.  If you agree, let's add name to the two entries tables and update the POST methods to get the name from the foods/reactions table and insert it into the entries table.  Once this is implemented, we can test this PR and merge accordingly.  Thanks.

**Comment by prestonjarnagin** [comment]
@mngatewood We can talk about this in standup, but I think we should update the food_id instead of adding a name field. If we added a name it would create some redundancy in the database. We can use that endpoint to try to update the food_entry's reference to the food table, and if a food doesn't yet exist, the endpoint can create a new one and update it to that.
For example, if I want to update a 'Coffee' to be 'Coffee with Cream', I can send a PATCH to update the name. The backend will see there's no 'Coffee with Cream' on the foods table, create the 'Coffee with Cream' food, and update the food_entry to reference the new food.

**Comment by mngatewood** [comment]
@prestonjarnagin @Diazblack @Q-Win I like this.  So when user wants to update the name associated with a particular food/reaction entry, the app will attempt to POST a new food/reaction.  If the food doesn't exist, BE will respond with the new ID.  If the food already exists, the BE will respond with the ID of the food.  Then the FE app will take that ID and send a PATCH request to food_entries/reaction_entries/:id with body{food_id/reaction_id: ##, date "###########"}.  BE will respond with a status.  Does this make sense?

**Comment by mngatewood** [comment]
@prestonjarnagin @Diazblack @Q-Win Solution implemented.  Requesting review.

**Comment by prestonjarnagin** [comment]
Looks good to me!

**Review by prestonjarnagin — APPROVED** [review]

**Review by Q-Win — APPROVED** [review]

**Comment by Diazblack** [comment]
@mngatewood  I think it make sense, If the food doesn't exist the BE can create the entry and send it back with the response, and it won't be that hard to change. What you guys think @Q-Win @prestonjarnagin

**Review by Diazblack — APPROVED** [review]

**Comment by Diazblack** [comment]
Approved

**Pull request merged**
